apiVersion: v1
kind: Namespace
metadata:
  name: h-console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: h-console-agent
  namespace: h-console
  labels:
    app: h-console-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: h-console-agent
  template:
    metadata:
      labels:
        app: h-console-agent
    spec:
      serviceAccountName: agent-serviceaccount
      containers:
        - name: agent
          image: ghcr.io/hwan001/h-console-agent:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENV
              value: "production"
            - name: BE_GRPC_ADDR
              value: "be-server:50051"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-serviceaccount
  namespace: h-console
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent-node-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agent-node-reader
subjects:
  - kind: ServiceAccount
    name: agent-serviceaccount
    namespace: h-console