version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: mydb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - internal_net

  hasura:
    image: hasura/graphql-engine:v2.40.0
    container_name: hasura
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:supersecret@postgres:5432/mydb
      HASURA_GRAPHQL_ADMIN_SECRET: myhasurasecret
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge