spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: hconsole

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        hibernate: DEBUG

hasura:
  graphql:
    endpoint: ${HASURA_ENDPOINT}
    admin-secret: ${HASURA_SECRET}

grpc:
  server:
    port: 9090