---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: hconsole
  namespace: flux-system
spec:
  interval: 1m
  image: ghcr.io/hwan001/hconsole
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: hconsole-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hconsole
  policy:
    semver:
      range: 0.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: hconsole
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: infra
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: flux-bot
        email: flux-bot@example.com
    push:
      branch: main
  update:
    path: ./deploy/gitops/apps/hconsole
    strategy: Setters
