redis:
  enabled: true
  image:
    repository: redis
    tag: "7.4"
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    port: 6379
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi