# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstream.proto\x12\x08hconsole\"\x89\x01\n\x08NodeInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x10\n\x08hostname\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x10\n\x08\x63puUsage\x18\x05 \x01(\x01\x12\x13\n\x0bmemoryUsage\x18\x06 \x01(\x01\x12\x0e\n\x06status\x18\x07 \x01(\t\x12\x0e\n\x06uptime\x18\x08 \x01(\t\">\n\x06Metric\x12!\n\x05nodes\x18\x01 \x03(\x0b\x32\x12.hconsole.NodeInfo\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\"8\n\x03Log\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\r\n\x05level\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"o\n\rStreamPayload\x12\x11\n\tclusterId\x18\x01 \x01(\t\x12\"\n\x06metric\x18\x02 \x01(\x0b\x32\x10.hconsole.MetricH\x00\x12\x1c\n\x03log\x18\x03 \x01(\x0b\x32\r.hconsole.LogH\x00\x42\t\n\x07payload\"\x1b\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\"2\n\x0e\x43ontrolMessage\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t2\x8f\x01\n\rStreamService\x12;\n\nSendStream\x12\x17.hconsole.StreamPayload\x1a\x12.hconsole.Response(\x01\x12\x41\n\x07\x43ontrol\x12\x18.hconsole.ControlMessage\x1a\x18.hconsole.ControlMessage(\x01\x30\x01\x42&\n\x15io.h001.hconsole.grpcB\x0bStreamProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025io.h001.hconsole.grpcB\013StreamProtoP\001'
  _globals['_NODEINFO']._serialized_start=27
  _globals['_NODEINFO']._serialized_end=164
  _globals['_METRIC']._serialized_start=166
  _globals['_METRIC']._serialized_end=228
  _globals['_LOG']._serialized_start=230
  _globals['_LOG']._serialized_end=286
  _globals['_STREAMPAYLOAD']._serialized_start=288
  _globals['_STREAMPAYLOAD']._serialized_end=399
  _globals['_RESPONSE']._serialized_start=401
  _globals['_RESPONSE']._serialized_end=428
  _globals['_CONTROLMESSAGE']._serialized_start=430
  _globals['_CONTROLMESSAGE']._serialized_end=480
  _globals['_STREAMSERVICE']._serialized_start=483
  _globals['_STREAMSERVICE']._serialized_end=626
# @@protoc_insertion_point(module_scope)
