name: Helm checks
on:
  pull_request:
    paths:
      - "deploy/gitops/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Check YAML formatting and validity
        run: yamllint deploy/gitops/

      - name: Scan Helm chart with kube-linter
        uses: stackrox/kube-linter-action@v1
        with:
          directory: deploy/gitops/apps
